import CustomToastContainer from "@/components/CustomToastContainer";
import Navbar from "@/components/Navbar";
import UserLoader from "@/components/UserLoader";
import UserProvider from "@/context/UserProvider";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Clínica Pompilio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <UserProvider>
            <UserLoader>
              <Navbar />
              {children}
            </UserLoader>
            <CustomToastContainer />
          </UserProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
